/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyWellspringsRouteImport } from './routes/why-wellsprings'
import { Route as TypographyRouteImport } from './routes/typography'
import { Route as ThemeOfTheYearRouteImport } from './routes/theme-of-the-year'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PhotographyRouteImport } from './routes/photography'
import { Route as MotionRouteImport } from './routes/motion'
import { Route as MandatoryDisclosureRouteImport } from './routes/mandatory-disclosure'
import { Route as LogoRouteImport } from './routes/logo'
import { Route as LifeRouteImport } from './routes/life'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as IllustrationRouteImport } from './routes/illustration'
import { Route as IconographyRouteImport } from './routes/iconography'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ColorRouteImport } from './routes/color'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CampusRouteImport } from './routes/campus'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BeyondBooksRouteImport } from './routes/beyond-books'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CurriculumIndexRouteImport } from './routes/curriculum.index'
import { Route as CurriculumSecondaryRouteImport } from './routes/curriculum.secondary'
import { Route as CurriculumPreparatoryRouteImport } from './routes/curriculum.preparatory'
import { Route as CurriculumMiddleRouteImport } from './routes/curriculum.middle'
import { Route as CurriculumFoundationRouteImport } from './routes/curriculum.foundation'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'

const WhyWellspringsRoute = WhyWellspringsRouteImport.update({
  id: '/why-wellsprings',
  path: '/why-wellsprings',
  getParentRoute: () => rootRouteImport,
} as any)
const TypographyRoute = TypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeOfTheYearRoute = ThemeOfTheYearRouteImport.update({
  id: '/theme-of-the-year',
  path: '/theme-of-the-year',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyRoute = PhotographyRouteImport.update({
  id: '/photography',
  path: '/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionRoute = MotionRouteImport.update({
  id: '/motion',
  path: '/motion',
  getParentRoute: () => rootRouteImport,
} as any)
const MandatoryDisclosureRoute = MandatoryDisclosureRouteImport.update({
  id: '/mandatory-disclosure',
  path: '/mandatory-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoRoute = LogoRouteImport.update({
  id: '/logo',
  path: '/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeRoute = LifeRouteImport.update({
  id: '/life',
  path: '/life',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const IllustrationRoute = IllustrationRouteImport.update({
  id: '/illustration',
  path: '/illustration',
  getParentRoute: () => rootRouteImport,
} as any)
const IconographyRoute = IconographyRouteImport.update({
  id: '/iconography',
  path: '/iconography',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorRoute = ColorRouteImport.update({
  id: '/color',
  path: '/color',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRoute = CampusRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BeyondBooksRoute = BeyondBooksRouteImport.update({
  id: '/beyond-books',
  path: '/beyond-books',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumIndexRoute = CurriculumIndexRouteImport.update({
  id: '/curriculum/',
  path: '/curriculum/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumSecondaryRoute = CurriculumSecondaryRouteImport.update({
  id: '/curriculum/secondary',
  path: '/curriculum/secondary',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumPreparatoryRoute = CurriculumPreparatoryRouteImport.update({
  id: '/curriculum/preparatory',
  path: '/curriculum/preparatory',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumMiddleRoute = CurriculumMiddleRouteImport.update({
  id: '/curriculum/middle',
  path: '/curriculum/middle',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumFoundationRoute = CurriculumFoundationRouteImport.update({
  id: '/curriculum/foundation',
  path: '/curriculum/foundation',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/beyond-books': typeof BeyondBooksRoute
  '/blog': typeof BlogRoute
  '/brand': typeof BrandRoute
  '/campus': typeof CampusRoute
  '/careers': typeof CareersRoute
  '/color': typeof ColorRoute
  '/contact': typeof ContactRoute
  '/iconography': typeof IconographyRoute
  '/illustration': typeof IllustrationRoute
  '/language': typeof LanguageRoute
  '/life': typeof LifeRoute
  '/logo': typeof LogoRoute
  '/mandatory-disclosure': typeof MandatoryDisclosureRoute
  '/motion': typeof MotionRoute
  '/photography': typeof PhotographyRoute
  '/resources': typeof ResourcesRoute
  '/theme-of-the-year': typeof ThemeOfTheYearRoute
  '/typography': typeof TypographyRoute
  '/why-wellsprings': typeof WhyWellspringsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/curriculum/foundation': typeof CurriculumFoundationRoute
  '/curriculum/middle': typeof CurriculumMiddleRoute
  '/curriculum/preparatory': typeof CurriculumPreparatoryRoute
  '/curriculum/secondary': typeof CurriculumSecondaryRoute
  '/curriculum/': typeof CurriculumIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/beyond-books': typeof BeyondBooksRoute
  '/blog': typeof BlogRoute
  '/brand': typeof BrandRoute
  '/campus': typeof CampusRoute
  '/careers': typeof CareersRoute
  '/color': typeof ColorRoute
  '/contact': typeof ContactRoute
  '/iconography': typeof IconographyRoute
  '/illustration': typeof IllustrationRoute
  '/language': typeof LanguageRoute
  '/life': typeof LifeRoute
  '/logo': typeof LogoRoute
  '/mandatory-disclosure': typeof MandatoryDisclosureRoute
  '/motion': typeof MotionRoute
  '/photography': typeof PhotographyRoute
  '/resources': typeof ResourcesRoute
  '/theme-of-the-year': typeof ThemeOfTheYearRoute
  '/typography': typeof TypographyRoute
  '/why-wellsprings': typeof WhyWellspringsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/curriculum/foundation': typeof CurriculumFoundationRoute
  '/curriculum/middle': typeof CurriculumMiddleRoute
  '/curriculum/preparatory': typeof CurriculumPreparatoryRoute
  '/curriculum/secondary': typeof CurriculumSecondaryRoute
  '/curriculum': typeof CurriculumIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/beyond-books': typeof BeyondBooksRoute
  '/blog': typeof BlogRoute
  '/brand': typeof BrandRoute
  '/campus': typeof CampusRoute
  '/careers': typeof CareersRoute
  '/color': typeof ColorRoute
  '/contact': typeof ContactRoute
  '/iconography': typeof IconographyRoute
  '/illustration': typeof IllustrationRoute
  '/language': typeof LanguageRoute
  '/life': typeof LifeRoute
  '/logo': typeof LogoRoute
  '/mandatory-disclosure': typeof MandatoryDisclosureRoute
  '/motion': typeof MotionRoute
  '/photography': typeof PhotographyRoute
  '/resources': typeof ResourcesRoute
  '/theme-of-the-year': typeof ThemeOfTheYearRoute
  '/typography': typeof TypographyRoute
  '/why-wellsprings': typeof WhyWellspringsRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/curriculum/foundation': typeof CurriculumFoundationRoute
  '/curriculum/middle': typeof CurriculumMiddleRoute
  '/curriculum/preparatory': typeof CurriculumPreparatoryRoute
  '/curriculum/secondary': typeof CurriculumSecondaryRoute
  '/curriculum/': typeof CurriculumIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admissions'
    | '/beyond-books'
    | '/blog'
    | '/brand'
    | '/campus'
    | '/careers'
    | '/color'
    | '/contact'
    | '/iconography'
    | '/illustration'
    | '/language'
    | '/life'
    | '/logo'
    | '/mandatory-disclosure'
    | '/motion'
    | '/photography'
    | '/resources'
    | '/theme-of-the-year'
    | '/typography'
    | '/why-wellsprings'
    | '/blog/$slug'
    | '/curriculum/foundation'
    | '/curriculum/middle'
    | '/curriculum/preparatory'
    | '/curriculum/secondary'
    | '/curriculum/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admissions'
    | '/beyond-books'
    | '/blog'
    | '/brand'
    | '/campus'
    | '/careers'
    | '/color'
    | '/contact'
    | '/iconography'
    | '/illustration'
    | '/language'
    | '/life'
    | '/logo'
    | '/mandatory-disclosure'
    | '/motion'
    | '/photography'
    | '/resources'
    | '/theme-of-the-year'
    | '/typography'
    | '/why-wellsprings'
    | '/blog/$slug'
    | '/curriculum/foundation'
    | '/curriculum/middle'
    | '/curriculum/preparatory'
    | '/curriculum/secondary'
    | '/curriculum'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admissions'
    | '/beyond-books'
    | '/blog'
    | '/brand'
    | '/campus'
    | '/careers'
    | '/color'
    | '/contact'
    | '/iconography'
    | '/illustration'
    | '/language'
    | '/life'
    | '/logo'
    | '/mandatory-disclosure'
    | '/motion'
    | '/photography'
    | '/resources'
    | '/theme-of-the-year'
    | '/typography'
    | '/why-wellsprings'
    | '/blog_/$slug'
    | '/curriculum/foundation'
    | '/curriculum/middle'
    | '/curriculum/preparatory'
    | '/curriculum/secondary'
    | '/curriculum/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  BeyondBooksRoute: typeof BeyondBooksRoute
  BlogRoute: typeof BlogRoute
  BrandRoute: typeof BrandRoute
  CampusRoute: typeof CampusRoute
  CareersRoute: typeof CareersRoute
  ColorRoute: typeof ColorRoute
  ContactRoute: typeof ContactRoute
  IconographyRoute: typeof IconographyRoute
  IllustrationRoute: typeof IllustrationRoute
  LanguageRoute: typeof LanguageRoute
  LifeRoute: typeof LifeRoute
  LogoRoute: typeof LogoRoute
  MandatoryDisclosureRoute: typeof MandatoryDisclosureRoute
  MotionRoute: typeof MotionRoute
  PhotographyRoute: typeof PhotographyRoute
  ResourcesRoute: typeof ResourcesRoute
  ThemeOfTheYearRoute: typeof ThemeOfTheYearRoute
  TypographyRoute: typeof TypographyRoute
  WhyWellspringsRoute: typeof WhyWellspringsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CurriculumFoundationRoute: typeof CurriculumFoundationRoute
  CurriculumMiddleRoute: typeof CurriculumMiddleRoute
  CurriculumPreparatoryRoute: typeof CurriculumPreparatoryRoute
  CurriculumSecondaryRoute: typeof CurriculumSecondaryRoute
  CurriculumIndexRoute: typeof CurriculumIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-wellsprings': {
      id: '/why-wellsprings'
      path: '/why-wellsprings'
      fullPath: '/why-wellsprings'
      preLoaderRoute: typeof WhyWellspringsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typography': {
      id: '/typography'
      path: '/typography'
      fullPath: '/typography'
      preLoaderRoute: typeof TypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme-of-the-year': {
      id: '/theme-of-the-year'
      path: '/theme-of-the-year'
      fullPath: '/theme-of-the-year'
      preLoaderRoute: typeof ThemeOfTheYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography': {
      id: '/photography'
      path: '/photography'
      fullPath: '/photography'
      preLoaderRoute: typeof PhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motion': {
      id: '/motion'
      path: '/motion'
      fullPath: '/motion'
      preLoaderRoute: typeof MotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mandatory-disclosure': {
      id: '/mandatory-disclosure'
      path: '/mandatory-disclosure'
      fullPath: '/mandatory-disclosure'
      preLoaderRoute: typeof MandatoryDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo': {
      id: '/logo'
      path: '/logo'
      fullPath: '/logo'
      preLoaderRoute: typeof LogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life': {
      id: '/life'
      path: '/life'
      fullPath: '/life'
      preLoaderRoute: typeof LifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/illustration': {
      id: '/illustration'
      path: '/illustration'
      fullPath: '/illustration'
      preLoaderRoute: typeof IllustrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iconography': {
      id: '/iconography'
      path: '/iconography'
      fullPath: '/iconography'
      preLoaderRoute: typeof IconographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color': {
      id: '/color'
      path: '/color'
      fullPath: '/color'
      preLoaderRoute: typeof ColorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus': {
      id: '/campus'
      path: '/campus'
      fullPath: '/campus'
      preLoaderRoute: typeof CampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beyond-books': {
      id: '/beyond-books'
      path: '/beyond-books'
      fullPath: '/beyond-books'
      preLoaderRoute: typeof BeyondBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/': {
      id: '/curriculum/'
      path: '/curriculum'
      fullPath: '/curriculum/'
      preLoaderRoute: typeof CurriculumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/secondary': {
      id: '/curriculum/secondary'
      path: '/curriculum/secondary'
      fullPath: '/curriculum/secondary'
      preLoaderRoute: typeof CurriculumSecondaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/preparatory': {
      id: '/curriculum/preparatory'
      path: '/curriculum/preparatory'
      fullPath: '/curriculum/preparatory'
      preLoaderRoute: typeof CurriculumPreparatoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/middle': {
      id: '/curriculum/middle'
      path: '/curriculum/middle'
      fullPath: '/curriculum/middle'
      preLoaderRoute: typeof CurriculumMiddleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/foundation': {
      id: '/curriculum/foundation'
      path: '/curriculum/foundation'
      fullPath: '/curriculum/foundation'
      preLoaderRoute: typeof CurriculumFoundationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  BeyondBooksRoute: BeyondBooksRoute,
  BlogRoute: BlogRoute,
  BrandRoute: BrandRoute,
  CampusRoute: CampusRoute,
  CareersRoute: CareersRoute,
  ColorRoute: ColorRoute,
  ContactRoute: ContactRoute,
  IconographyRoute: IconographyRoute,
  IllustrationRoute: IllustrationRoute,
  LanguageRoute: LanguageRoute,
  LifeRoute: LifeRoute,
  LogoRoute: LogoRoute,
  MandatoryDisclosureRoute: MandatoryDisclosureRoute,
  MotionRoute: MotionRoute,
  PhotographyRoute: PhotographyRoute,
  ResourcesRoute: ResourcesRoute,
  ThemeOfTheYearRoute: ThemeOfTheYearRoute,
  TypographyRoute: TypographyRoute,
  WhyWellspringsRoute: WhyWellspringsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CurriculumFoundationRoute: CurriculumFoundationRoute,
  CurriculumMiddleRoute: CurriculumMiddleRoute,
  CurriculumPreparatoryRoute: CurriculumPreparatoryRoute,
  CurriculumSecondaryRoute: CurriculumSecondaryRoute,
  CurriculumIndexRoute: CurriculumIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
